Implement the saving of schedule to JSON file
AY2324S1-CS2103T-T11-3/tp pull request #97
Opened 2023-10-24 08:59 UTC by HollaG

Fixes #67. 

Changelog
1. Added the save file logic to LogicManager.java
2. Changed the Parse command to return a Subject with Subject.Subjects.None instead of null to prevent NullPointerException when trying to serialize Subject
3. Added a new method in Subject to create a Subject with Subject.Subjects.None (this is used in the above change)

2023-10-24 16:23 UTC, elaineshijie approved these changes
LGTM!

2023-10-24 16:24 UTC, elaineshijie commented
Fixes #62

2023-10-25 01:25 UTC, yiwen101 requested changes
Please try to improve the codecov a bit, should be easy.
We realize (to our horror) recently that we might be penalized for merging PR failing codecov (unless for exceptional reason, for example, Richie achieved 100% codecov for modified lines in his show command PR but still failing project codecov, then no choice but merge; UI cannot be easily automatically tested, then no choice but merge)

2023-10-25 01:25 UTC, yiwen101 commented on src/main/java/seedu/address/logic/parser/TypeParsingUtil.java
> -            return null;
This will break the current add/edit class, as they are updated via "setIfNotNull" method.

2023-10-25 01:26 UTC, yiwen101 commented on src/main/java/seedu/address/logic/parser/TypeParsingUtil.java
> -            return null;
Upon reflection, I think it is my fault not articulating the dependence of parser classes on model items. So I want to create an abstract class/interface and make all of the parsable subjects in model extend/implement it. Are you good with that?

2023-10-25 12:12 UTC, yiwen101 commented on src/main/java/seedu/address/logic/parser/TypeParsingUtil.java
> -            return null;
Good news, there is a potential release on the requirement for codecov for now, as seen from  https://www.github.com/nus-cs2103-AY2324S1/forum/issues/281 (credit to Richie for pointing this out). I posted a following up question in the forum to clarify, will revoke my request for change for adding more tests on getting positive response from prof.

2023-10-25 15:32 UTC, yiwen101 approved these changes

2023-10-25 15:32 UTC, merged